export let dummyInfo = [
    {
      id: '000db964-719d-4532-9225-35658565b35d',
      card_name: 'Narset, Parter of Veils',
      img: 'https://cards.scryfall.io/large/front/0/0/000db964-719d-4532-9225-35658565b35d.jpg?1666939107',
      mana_cost: '{1}{U}{U}',
      cmc: 3,
      power: null,
      toughness: null,
      colors: [ 'U' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'not_legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'legal',
        vintage: 'restricted',
        explorer: 'legal',
        historic: 'legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Secret Lair Drop',
      rarity: 'rare',
      artist: 'Uta Natsume',
      price: null,
      type: 'Legendary Planeswalker — Narset',
      quantity: 2
    },
    {
      id: '013f03fa-4b49-4709-8f6b-415af3e6dd09',
      card_name: "Urza's Sylex",
      img: 'https://cards.scryfall.io/large/front/0/1/013f03fa-4b49-4709-8f6b-415af3e6dd09.jpg?1675621696',
      mana_cost: '{3}',
      cmc: 3,
      power: null,
      toughness: null,
      colors: [],
      legality: {
        duel: 'legal',
        brawl: 'legal',
        penny: 'not_legal',
        predh: 'not_legal',
        future: 'legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'legal',
        pioneer: 'legal',
        vintage: 'legal',
        explorer: 'legal',
        historic: 'legal',
        standard: 'legal',
        commander: 'legal',
        gladiator: 'legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'legal',
        paupercommander: 'not_legal'
      },
      set_name: "The Brothers' War Promos",
      rarity: 'mythic',
      artist: 'Joseph Meehan',
      price: null,
      type: 'Legendary Artifact',
      quantity: 1
    },
    {
      id: '02d19fbe-0f6d-4e22-b56d-a63fd17a48ef',
      card_name: 'Dimir Guildmage',
      img: 'https://cards.scryfall.io/large/front/0/2/02d19fbe-0f6d-4e22-b56d-a63fd17a48ef.jpg?1562258499',
      mana_cost: '{U/B}{U/B}',
      cmc: 2,
      power: 2,
      toughness: 2,
      colors: [ 'B', 'U' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'legal',
        predh: 'legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'not_legal',
        paupercommander: 'legal'
      },
      set_name: 'Modern Masters 2015',
      rarity: 'uncommon',
      artist: 'Adam Rex',
      price: '0.02',
      type: 'Creature — Human Wizard',
      quantity: 2
    },
    {
      id: '02e58076-86a3-4bf1-a3e4-8b53a4e93543',
      card_name: 'Sarkhan the Mad',
      img: 'https://cards.scryfall.io/large/front/0/2/02e58076-86a3-4bf1-a3e4-8b53a4e93543.jpg?1583453947',
      mana_cost: '{3}{B}{R}',
      cmc: 5,
      power: null,
      toughness: null,
      colors: [ 'B', 'R' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'legal',
        predh: 'legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'not_legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Mystery Booster Retail Edition Foils',
      rarity: 'mythic',
      artist: 'Chippy',
      price: null,
      type: 'Legendary Planeswalker — Sarkhan',
      quantity: 1
    },
    {
      id: '04c01143-f7fc-4874-87fd-59d1432c2bbb',
      card_name: "Estrid's Invocation",
      img: 'https://cards.scryfall.io/large/front/0/4/04c01143-f7fc-4874-87fd-59d1432c2bbb.jpg?1592710073',
      mana_cost: '{2}{U}',
      cmc: 3,
      power: null,
      toughness: null,
      colors: [ 'U' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'not_legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'not_legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'not_legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Commander 2018',
      rarity: 'rare',
      artist: 'Johannes Voss',
      price: '9.93',
      type: 'Enchantment',
      quantity: 2
    },
    {
      id: '04d2f5e2-fb95-48b0-b7bf-689d45fa8970',
      card_name: 'Mesa Falcon',
      img: 'https://cards.scryfall.io/large/front/0/4/04d2f5e2-fb95-48b0-b7bf-689d45fa8970.jpg?1562587033',
      mana_cost: '{1}{W}',
      cmc: 2,
      power: 1,
      toughness: 1,
      colors: [ 'W' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'not_legal',
        pauper: 'legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'legal',
        oathbreaker: 'legal',
        historicbrawl: 'not_legal',
        paupercommander: 'legal'
      },
      set_name: 'Homelands',
      rarity: 'common',
      artist: 'Mark Poole',
      price: '0.05',
      type: 'Creature — Bird',
      quantity: 2
    },
    {
      id: '04d5d429-e0c6-42cc-a477-da7dabb1c295',
      card_name: 'Leyline of the Void',
      img: 'https://cards.scryfall.io/large/front/0/4/04d5d429-e0c6-42cc-a477-da7dabb1c295.jpg?1592516724',
      mana_cost: '{2}{B}{B}',
      cmc: 4,
      power: null,
      toughness: null,
      colors: [ 'B' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'legal',
        vintage: 'legal',
        explorer: 'legal',
        historic: 'legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Core Set 2020',
      rarity: 'rare',
      artist: 'Noah Bradley',
      price: '5.76',
      type: 'Enchantment',
      quantity: 3
    },
    {
      id: '04d6b47f-5c2a-4771-90ee-4aa8c1eda0be',
      card_name: 'Construct',
      img: 'https://cards.scryfall.io/large/front/0/4/04d6b47f-5c2a-4771-90ee-4aa8c1eda0be.jpg?1561756590',
      mana_cost: '',
      cmc: 0,
      power: 6,
      toughness: 12,
      colors: [],
      legality: {
        duel: 'not_legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'not_legal',
        future: 'not_legal',
        legacy: 'not_legal',
        modern: 'not_legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'not_legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'not_legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'not_legal',
        historicbrawl: 'not_legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Worldwake Tokens',
      rarity: 'common',
      artist: 'Jung Park',
      price: null,
      type: 'Token Artifact Creature — Construct',
      quantity: 3
    },
    {
      id: '062fcd2b-7f63-47bf-83ba-88e33d397a6e',
      card_name: 'Chromatic Orrery',
      img: 'https://cards.scryfall.io/large/front/0/6/062fcd2b-7f63-47bf-83ba-88e33d397a6e.jpg?1596311513',
      mana_cost: '{7}',
      cmc: 7,
      power: null,
      toughness: null,
      colors: [],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'not_legal',
        predh: 'not_legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'legal',
        vintage: 'legal',
        explorer: 'legal',
        historic: 'legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Core Set 2021 Promos',
      rarity: 'mythic',
      artist: 'Volkan Baǵa',
      price: '9.40',
      type: 'Legendary Artifact',
      quantity: 3
    },
    {
      id: '066b677d-5a4c-4bb4-a3e0-1e616aafb9da',
      card_name: 'Ulasht, the Hate Seed',
      img: 'https://cards.scryfall.io/large/front/0/6/066b677d-5a4c-4bb4-a3e0-1e616aafb9da.jpg?1551119665',
      mana_cost: '{2}{R}{G}',
      cmc: 4,
      power: 0,
      toughness: 0,
      colors: [ 'G', 'R' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'legal',
        predh: 'legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'not_legal',
        vintage: 'legal',
        explorer: 'not_legal',
        historic: 'not_legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'not_legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'not_legal',
        paupercommander: 'not_legal'
      },
      set_name: 'RNA Guild Kit',
      rarity: 'rare',
      artist: 'Nottsuo',
      price: '0.49',
      type: 'Legendary Creature — Hellion Hydra',
      quantity: 1
    },
    {
      id: '1d3d8bb4-0430-45bb-930d-5d6db6521945',
      card_name: 'Etali, Primal Storm',
      img: 'https://cards.scryfall.io/large/front/1/d/1d3d8bb4-0430-45bb-930d-5d6db6521945.jpg?1587309687',
      mana_cost: '{4}{R}{R}',
      cmc: 6,
      power: 6,
      toughness: 6,
      colors: [ 'R' ],
      legality: {
        duel: 'legal',
        brawl: 'not_legal',
        penny: 'legal',
        predh: 'not_legal',
        future: 'not_legal',
        legacy: 'legal',
        modern: 'legal',
        pauper: 'not_legal',
        alchemy: 'not_legal',
        pioneer: 'legal',
        vintage: 'legal',
        explorer: 'legal',
        historic: 'legal',
        standard: 'not_legal',
        commander: 'legal',
        gladiator: 'legal',
        oldschool: 'not_legal',
        premodern: 'not_legal',
        oathbreaker: 'legal',
        historicbrawl: 'legal',
        paupercommander: 'not_legal'
      },
      set_name: 'Rivals of Ixalan',
      rarity: 'rare',
      artist: 'Raymond Swanland',
      price: '0.65',
      type: 'Legendary Creature — Elder Dinosaur',
      quantity: 2
    }
  ]